name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa 206.189.140.88 >> ~/.ssh/known_hosts
        ssh-add ~/.ssh/id_rsa

    - name: Install PHP & Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        composer install
        npm install
        npm run production

    - name: Deploy to server
      run: |
        rsync -avz --delete --exclude .git . your_username@your_server_ip:/path/to/your/laravel/app
